# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Ryan Cordell
paginate:       5
baseurl:        ""
url:            "https://rccordell.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Ryan Cordell
  url:          http://ryancordell.org
  email:        rccordell@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/rccordell/

# List of links in the navigation bar 
navbar-links:
  About: "about"
  Teaching: "teaching"
  CV: "http://cv.ryancordell.org"
  Tweet: "https://twitter.com/ryancordell"
  Viral Texts: "http://viraltexts.org"
  Oceanic Exchanges: "http://oceanicexchanges.org"

# Gems
gems:
  - jekyll-paginate
